#!/usr/bin/env bash
# install and configure HAproxy on a new server to act as a loadbalancer between web-01 and web-02

sudo apt -y update && sudo apt -y upgrade
sudo apt install haproxy -y
sudo service haproxy start
sudo chown -R "$USER":"$USER" /etc/haproxy
sudo chmod -R 755 /etc/haproxy

sudo echo "
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend myfrontend
    bind *:80
    default_backend mybackend

backend mybackend
    balance roundrobin
    server 161051-web-01 52.201.211.220:80 check
    server 161051-web-02 100.25.46.99:80 check

" | sudo tee /etc/haproxy/haproxy.cfg

sudo chown -R "$USER":"$USER" /etc/default
sudo chmod -R 755 /etc/default
sudo echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo service haproxy restart
