#!/usr/bin/env bash
# script to dump mysql and create a tar file from dump file

file_name="$(date +'%d-%m-%Y').tar.gz"
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
