#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line
a=0
while [ $a -lt 10 ]
do
    echo "Best School"
    if [ $a -eq 8 ];
    then
        echo "Hi"
    fi
    a=$((a + 1))
done
